# Name the Analysis
ANALYSIS: # name

# Choose yes if trimming is required
TRIM: "yes" # or "no"

# Choose yes if samples are xenografts
XENO_FILTER: "yes" # or "no"

ADAPTERS: "/path/to/adapters.fa"
RAW_PATH: "/path/to/raw reads (fastq.gz)"
TRIM_PATH: "/SWIS-META/transcriptomics/snake_out/trimmomatic"
OUT: "/SWIS-META/transcriptomics/snake_out"
GTF_FILE: "/path/to/Homo_sapiens.GRCh38.104.gtf"
OUT_FINAL: "/SWIS-META/transcriptomics/snake_out_final"
INDEX_PATH: "/path/to/index_directory"
HOST_DB: "/path/to/Mus_musculus.GRCm39.dna.primary_assembly.fa"
GRAFT_DB: "/path/to/Homo_sapiens.GRCh38.dna.primary_assembly.fa"
HISAT_INDEX: "/SWIS-META/transcriptomics/index/hisat2_index"
HISAT_PATH: "/SWIS-META/transcriptomics/index/hisat2_index/GRCh38"
COUNT_DIR: "/SWIS-META/transcriptomics/counts"
XENO_DIR: "/SWIS-META/transcriptomics/snake_out/xeno_filtered"


# de analysis paths
count_matrix_path: "path/to/gene_symbol_counts_matrix.csv"
metadata_path: "path/to/metadata.csv"
output_dir: "/path/to/output_dir"

