ANALYSIS: test
TRIM: "yes"
XENO_FILTER: "yes"
ADAPTERS: "/users/2875659p/sharedscratch/rna_seq/trimmomatic/adapters.fa"
RAW_PATH: "/users/2875659p/sharedscratch/rna_seq"
TRIM_PATH: "/users/2875659p/sharedscratch/rna_seq/transcriptomics/snake_out/trimmomatic"
OUT: "/users/2875659p/sharedscratch/rna_seq/transcriptomics/snake_out"
GTF_FILE: "/users/2875659p/sharedscratch/rna_seq/Databases/Homo_sapiens.GRCh38.104.gtf"
OUT_FINAL: "/users/2875659p/sharedscratch/rna_seq/transcriptomics/snake_out_final"
INDEX_PATH: "/users/2875659p/sharedscratch/rna_seq/transcriptomics/index"
HOST_DB: "/users/2875659p/sharedscratch/rna_seq/Databases/Mus_musculus.GRCm39.dna.primary_assembly.fa"
GRAFT_DB: "/users/2875659p/sharedscratch/rna_seq/Databases/Homo_sapiens.GRCh38.dna.primary_assembly.fa"
HISAT_INDEX: "/users/2875659p/sharedscratch/rna_seq/transcriptomics/index/hisat2_index"
HISAT_PATH: "/users/2875659p/sharedscratch/rna_seq/transcriptomics/index/hisat2_index/GRCh38"
COUNT_DIR: "/users/2875659p/sharedscratch/rna_seq/transcriptomics/counts"
XENO_DIR: "/users/2875659p/sharedscratch/rna_seq/transcriptomics/snake_out/xeno_filtered"
