#!/bin/bash -l

############# SLURM SETTINGS #############

#SBATCH --account=none
#SBATCH --job-name=snake_2
#SBATCH --partition=nodes
#SBATCH --time=0-12:00:00
#SBATCH --mem=64G
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --ntasks-per-node=1
#SBATCH --mail-user=2875659p@student.gla.ac.uk
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL

###############################################
# load modules

module load apps/R/4.4.0/gcc-13.1.0+openblas-0.3.21
# Run snakemake
snakemake -s Snakefile --cores $SLURM_CPUS_PER_TASK --use-conda
